version: '3'
services:
  rproxy:
    build: ./rproxy/
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./docker-volumes/cert_bot/certs/:/etc/letsencrypt/
      - ./docker-volumes/cert_bot/certs_data/:/var/www/certbot/
    depends_on: 
      - api
      - web

  api:
    build: ./backend/
    restart: always
    ports:
      - 8080:3000
    depends_on: 
      - db

  web:
    build: ./frontend/
    restart: always
    ports:
      - 81:80
      - 444:443
    depends_on: 
      - api

  db:
    image: mysql
    volumes:
      - ./docker-volumes/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'api-backend'
      MYSQL_PASSWORD: 'testpassword'
      MYSQL_DATABASE: 'healthcare'
    security_opt:
      - seccomp:unconfined